### ISSUE TITLE
Control x location isn't offset with the parent's location

### ISSUE THREAD

**Issue by ysl3000** [NickAcPT/Lithium#16]
# Lithium Issue
### Faulty Component (Forge Mod, Spigot Plugin or Backend)
Backend and Forge

---
### Expected behaviour

Encapsulated GUI elements position should be oriented at parent element.

expressed in CSS: relative

---
### Actual behaviour

Element is oriented at window.
expressed in CSS: absolute

(edited by NickAc to fix formatting)

**Comment by NickAcPT** [comment]
Hello, thank you for your issue report.
Your issue is being analysed and I may answer later with more details.

---
Thank you, NickAc.

**Comment by NickAcPT** [comment]
Actually, components are rendered relative to their parent location.
If you go to the Forge-Mod code and go to the class NewLithiumGUI.java ([link](https://github.com/NickAcPT/Lithium-Forge/blob/e90f8a7b9d4b164a262afe66e631ebd2542c0ae8/src/main/java/net/nickac/lithium/frontend/mod/ui/NewLithiumGUI.java#L85))
The controls' positions are relative to the parent container.
Just to be sure, does the bug only occur on the X axis (while not centered)?
If the answer is yes, I found the culprit. [This line](https://github.com/NickAcPT/Lithium-Forge/blob/e90f8a7b9d4b164a262afe66e631ebd2542c0ae8/src/main/java/net/nickac/lithium/frontend/mod/ui/NewLithiumGUI.java#L97) doesn't have the parent loc appended to it.
This is because we don't account for it when centering. A fix would be to append the parentLoc.X value when not centered on the X axis.

**Comment by NickAcPT** [comment]
If we wan't to get the most correct option, we must change that method to allow for window centering (whole screen), or parent centering.

**Comment by ysl3000** [comment]
I fixed the x-axis. Now it’s working when using coordinates. 
Parent getBottom()+5 and ..getRight()+5 currently doesn’t wor as intended. 
+5 is a manual defined  margin. I’m looking into it.

**Comment by NickAcPT** [comment]
> Parent getBottom()+5 and ..getRight()+5 currently doesn’t wor as intended.

Of course that doesn't work. By adding 5 to the bottom and right, you are going out of bounds.

**Comment by ysl3000** [comment]
https://github.com/NickAcPT/Lithium-Forge/blob/e90f8a7b9d4b164a262afe66e631ebd2542c0ae8/src/main/java/net/nickac/lithium/frontend/mod/ui/NewLithiumGUI.java#L97

is now fixed as well.

https://github.com/NickAcPT/Lithium-Forge/blob/master/src/main/java/net/nickac/lithium/frontend/mod/ui/NewLithiumGUI.java#L99

**Comment by NickAcPT** [comment]
Thank you for pointing it out.
Your help with this project is amazing. **Thank you!**
